language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "nightly"
matrix:
  allow_failures:
    - python: "nightly"
addons:
  apt:
    packages:
      - debhelper
      - devscripts
      - zsh
script:
  - ./tests/ci-test-wrapper --watch .travis.yml
  - git fetch --tags origin
  - ./tools/makedeb
deploy:
  provider: releases
  api-key:
    secure: g00YmDCb9gszABGJfzTyWeSy6zvvHCRI+vVjvJV7ubgs7L3JUeXfIfLeHZ4fUCX6RjhsOMwgQIIJVVtK5kgUI9YkBRJWdVo7jmJRefkxwTu2SF5SwDjYumiE6mqQlGCfo7OcV0/a/T5ipt5JyBUtY7DIMB2/wyz3jLPCvx4/aQo6COw0tKzaXgiXm0eJz6biEkc3QwGkFUNJFKgmvuvi+FYBJU21fD4cto8ck9i/0IUjsGxbExSpMKbe8bKj3BVh4dyMvZ6e+I/y2l2MM/RazssgFpiqabBm61CL4XCKxXzBsOgjhHSts7y+oWD3YnQqeaeugO5c6d8NPF5LSQk6VYEWYNwt3tdov/6zMMJohyN975AncjtwISzFzBZhAcXUeFxzs+6lfdNZc5lCE9gl+G9gUjWQ/0xyEFtT3m3kyjLlofoqiLwGv/+liaFSSxUpQd2ZHu5OoRjHcCJlxDd+9ppFDjV267zaa4eVBut87PP0QamUWSHEQW4tIuWLujCgJOn+IAMJTppNJ06q5RShV3ilbwlL+SkDSRUS79bLn5ELEgFADTJtUZwLU33VsYgTJ2Ktauu27kvjGitVTR+MgRzc2MVY1Gm6wN8AIe1HQj9YV0ePFp656Q8W29UnuN3QAfPwi2o5SimkNTrtp3MtQhq2nCBB5WqDv5L+DEwj654=
  file_glob: true
  file: dist/*.deb
  on:
    repo: jarun/googler
    tags: true
    # Upload from only one job (doesn't matter which one because we're packaging the same thing throughout the matrix)
    python: "2.7"
